using MainApp.Domain.Models;
Console.ForegroundColor = ConsoleColor.DarkCyan;
PetStoreGeneric<Dog> dogStore = new PetStoreGeneric<Dog>();
dogStore.AddPet(new Dog("Bob", 3, true, "Chicken"));
dogStore.AddPet(new Dog("Max", 2, true, "Beef"));
dogStore.PrintPets();
PetStoreGeneric<Cat> catStore = new PetStoreGeneric<Cat>();
catStore.AddPet(new Cat("Tom", 4, true, 7));
catStore.AddPet(new Cat("Mjau", 5, false, 9));
catStore.PrintPets();
PetStoreGeneric<Fish> fishStore = new PetStoreGeneric<Fish>();
fishStore.AddPet(new Fish("Delfina", 1, "Gold", "Small"));
fishStore.AddPet(new Fish("Plavusa", 2, "Blue", "Medium"));
fishStore.PrintPets();
dogStore.BuyPet("Bob");
catStore.BuyPet("Tom");
fishStore.BuyPet("Delfina");
dogStore.BuyPet("Pero");
catStore.BuyPet("Crni");
fishStore.BuyPet("Ajkulita");
Console.ReadLine();